### ISSUE TITLE
Nginx entered FATAL state

### ISSUE THREAD

**Issue by jhonore** [lwolf/gitlab-chart#8]
Hi guys,

I've got some problems with the chart installation.
```yaml
version: 0.2.5
```

<img width="297" alt="capture d ecran 2017-07-06 a 10 21 24" src="https://user-images.githubusercontent.com/18578614/27915617-e35d4374-6234-11e7-83a7-aab7a17443cd.png">

After deploying gitlab
```shell
helm install -f value-test.yaml lwolf-charts/gitlab --name gitlab --namespace=gitlab
```
With those values 
```yaml
serviceType: NodePort

sshPort: 22
httpPort: 80
httpsPort: 443


ingress:
  enabled: false
  configNamespaceOverride: "default"

  ## Gitlab Ingress annotations
  ##
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'

  ## Gitlab Ingress hostnames
  ## Must be provided if Ingress is enabled
  ##
  hosts:
    - gitlab.example.com

  ## Gitlab Ingress TLS configuration
  ## Secrets must be manually created in the namespace
  ##
  tls:
    - secretName: gitlab-server-tls
      hosts:
        - gitlab.example.com

persistence:
  ## This volume persists generated configuration files, keys, and certs.
  ##
  enabled: true
  size: 1Gi
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass: standard
  # storageClass: "slow"
  # accessMode: ReadWriteOnce


postgresql:
  image: "postgres"
  imageTag: "9.6.3-alpine"
  persistence:
    enabled: true
    # storageClass: "slow"
    size: 1Gi

redis:
  image: redis:3.2.9-alpine
  persistence:
    enabled: true
    # storageClass: "slow"
    size: 1Gi

minio:
  imagePullPolicy: "IfNotPresent"
  accessKey: "AKIAIOSFODNN7EXAMPLE"
  secretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  persistence:
    enabled: true
    # storageClass: "slow"
    size: 2Gi

config:
  DEBUG: "true"
  GITLAB_ROOT_EMAIL: "judes.honore@outlook.com"

  GITLAB_ROOT_PASSWORD: "3Uhprz35WEYCmebz56dyvLciwvzQxz"
  GITLAB_SECRETS_DB_KEY_BASE: "kCFSUsLlyZETCpStxxKG"
  GITLAB_SECRETS_SECRET_KEY_BASE: "gPL3l6dQ4FXo6a9fwa6I"
  GITLAB_SECRETS_OTP_KEY_BASE: "SVEHkkfIViQ4xDuNN8LM"

  GITLAB_HOST: gitlab.example.com
  GITLAB_PORT: 443
  GITLAB_TIMEZONE: "America/Martinique"
  GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: "186f6cdcb713adEXAMPLETOKEN"

  GITLAB_SSH_HOST: "git.example.com"
  GITLAB_SSH_PORT: "22"


  SMTP_ENABLED: false
  SMTP_DOMAIN: gitlab.example.com
  SMTP_HOST: smtp.mailgun.org
  SMTP_PORT: "587"
  SMTP_USER: admin
  SMTP_PASS: password
  SMTP_STARTTLS: "true"
  SMTP_AUTHENTICATION: login

  GITLAB_REGISTRY_ENABLED: true
  GITLAB_REGISTRY_HOST: dhub.example.com
  GITLAB_REGISTRY_PORT: 443
  GITLAB_REGISTRY_API_URL: https://dhub.example.com
  GITLAB_REGISTRY_KEY_PATH: /certs/tls.key
  SSL_REGISTRY_KEY_PATH: /certs/tls.key
  SSL_REGISTRY_CERT_PATH: /certs/tls.crt


runner:
  enabled: true
  image: gitlab/gitlab-runner:alpine-v9.2.2
  gitlabUrl: "https://gitlab.example.com/ci/"
  registrationToken: "186f6cdcb713adEXAMPLETOKEN"
  cache:
    enabled: true
    accessKey: "AKIAIOSFODNN7EXAMPLE"
    secretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

registry:
  enabled: true
  authTokenRealm: "https://gitlab.example.com/jwt/auth"
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'true'
    hosts:
      - dhub.example.com

  persistence:
    enabled: true
    size: 2Gi

```
See namespace content after deployement
<img width="692" alt="capture d ecran 2017-07-06 a 10 15 23" src="https://user-images.githubusercontent.com/18578614/27915388-2b25b156-6234-11e7-9abb-529016b73dc0.png">

See the gitlab-gitlab pod description
<img width="1386" alt="capture d ecran 2017-07-06 a 10 22 28" src="https://user-images.githubusercontent.com/18578614/27915778-37fb043e-6235-11e7-9775-ea487367a53f.png">

I've got this error inside gitlab-gitlab pod container
<img width="931" alt="capture d ecran 2017-07-06 a 09 43 15" src="https://user-images.githubusercontent.com/18578614/27915258-b89f6e38-6233-11e7-80b7-3212f5601135.png">

How i can solve this problem ?
Where i made a mistake ?
